sudo: required

script:
  - sudo docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:xenial /bin/sh build.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - sh upload.sh out/*

branches:
  except:
    - /^(?i:continuous)$/

notifications:
  email: false
