sudo: required

script:
  - sudo bash build.sh

after_success:
  - wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/znx

branches:
  except:
    - /^(?i:continuous)$/

notifications:
  email: false
