sudo: required

script:
  - sudo docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:xenial /bin/sh TRAVIS_COMMIT=$TRAVIS_COMMIT build.sh

after_success:
  - wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/znx

branches:
  except:
    - /^(?i:continuous)$/

notifications:
  email: false
